### ISSUE TITLE
Pararam os updates?

### ISSUE THREAD

**Issue by pperrot1** [marcuswac/covid-br-data#1]

**Comment by marcuswac** [comment]
o ministério da saúde mudou o formato do arquivo, tenho que arranjar um tempo para adaptar o script para manipular o novo formato. se alguém quiser contribuir com um Pull Request será muito bem vindo :)

**Comment by marcuswac** [comment]
fixed.

**Comment by pperrot1** [comment]
Obrigada!! Eu não manjo nada de Pull Requests! Mas seu dataset me ajuda bastante em um workflow de Alteryx!

**Comment by marcuswac** [comment]
Que bom que está sendo útil, achei que só eu estava usando. Vou tentar atualizar com mais frequência.
